env:
  TERM: xterm-256color

window:
  # Window padding (changes require restart)
  padding:
    x: 20
    y: 20

  # Window decorations
  #
  # Values for `decorations`:
  #   - full: Borders and title bar
  #   - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #   - transparent: Title bar, transparent background and title bar buttons
  #   - buttonless: Title bar, transparent background and no title bar buttons
  decorations: "buttonless"

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.95

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: "Windowed"

scrolling:
  history: 20000

font:
  normal:
    family: "HackGen Console NF"
    style: "Regular"
  bold:
    family: "HackGen Console NF"
    style: "Bold"
  italic:
    family: "HackGen Console NF"
    style: "Italic"
  bold_italic:
    family: "HackGen Console NF"
    style: "Bold Italic"
  size: 13.5
  offset:
    x: 2
    y: 4

colors:
  primary:
    background: "0x282828"
    foreground: "#afb4c3"
  normal:
    black: "#272b30"
    red: "#cc6666"
    green: "#bdb968"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b08cba"
    cyan: "#7fb2c8"
    white: "#afb4c3"

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "/opt/homebrew/bin/zellij attach --index 0 -c"

key_bindings:
  - { key: F, mods: Command|Control, action: ToggleSimpleFullscreen }
