[colors.normal]
black = "#272b30"
blue = "#81a2be"
cyan = "#7fb2c8"
green = "#bdb968"
magenta = "#b08cba"
red = "#cc6666"
white = "#afb4c3"
yellow = "#f0c674"

[colors.primary]
background = "0x282828"
foreground = "#afb4c3"

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold Italic"

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.offset]
x = 2
y = 4

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[scrolling]
history = 20000

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "/opt/homebrew/bin/zellij attach --index 0 -c"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 0.95
startup_mode = "Windowed"
option_as_alt = "Both"

[window.padding]
x = 20
y = 20
